### ISSUE TITLE
Snorkel installation fails: ResolvePackageNotFound: -pytorch

### ISSUE THREAD

**Issue by kalpmail** [HazyResearch/snorkel#1040] opened 2018-12-03 23:54 UTC
I am getting error even in the first step. Please note that I already installed XCode. 

Please see the attached Screen shot.
<img width="556" alt="screenshot 2018-12-03 17 54 32" src="https://user-images.githubusercontent.com/7083177/49409026-83633380-f724-11e8-90e9-4c3b2933ad72.png">

**Comment by kluikens** [comment] 2018-12-05 03:12
I hit this issue as well when installing from `master`, but was able to work around by following the instructions to install a release.

Can you reproduce the issue if you install the [v0.7.0-beta](https://github.com/HazyResearch/snorkel/releases/tag/v0.7.0-beta) release?

**Comment by kalpmail** [comment] 2018-12-05 17:42
I am getting error only with v0.7.0-beta release. I am following the instructions to install. Still not successful.

**Comment by Drakensberge** [comment] 2018-12-22 01:19
@kalpmail If you are on a Mac this may be duplicate of  https://github.com/HazyResearch/snorkel/issues/1043 
The replies there should fix it for you,

**Comment by kalpmail** [comment] 2018-12-26 16:04
Thank you so much everyone! I am able to install snorkel-0.7.0-beta. 

I did the following:
I downloaded snorkel-0.7.0-beta from https://github.com/HazyResearch/snorkel/releases/tag/v0.7.0-beta and unzipped the source code. 
I set the path for anaconda. Without this I got an error for the first installation instructions. 
I followed the installation instructions. 

Thanks again!

**Comment by bhancock8** [comment] 2019-02-19 05:07
I believe this is now fixed in #1063 with pytorch 1.0, which has a more forgiving installation process.

**Closed by bhancock8** 2019-02-19 05:07 UTC
