### ISSUE TITLE
ImportError: No module named 'snorkel'

### ISSUE THREAD

**Issue by Geldren1** [HazyResearch/snorkel#408] opened 2016-08-23 12:15 UTC
Hello all,

I am trying to execute the gene tagging example and I am stuck on step 1: Obtain and parse input data.
I am trying to import functions from the snorkel.parser module but keep getting an error as follows:

from snorkel.parser import HTMLDocParser
causes the following error:
ImportError                               Traceback (most recent call last)
<ipython-input-6-bddd39ec6a4f> in <module>()
----> 1 from snorkel.parser import HTMLDocParser

ImportError: No module named 'snorkel'

**Comment by ajratner** [comment] 2016-08-24 08:16
Hi @Geldren1 did you start up the notebook using the `run.sh` script?

**Comment by Geldren1** [comment] 2016-08-24 10:33
No, I'm using anaconda Navigator. 
I created a snorkel environment , added the required packages using the terminal and pip install --requirement python-package-requirement.txt
then I enabled ipywidgets  jupyter nbextension enable --p widgetsnbextention --sys-prefix. 
This returned an Import error: no module names widgetsbextension but I was not too worried as ipywidgets seemed to be active when I looked in anaconda navigator.

For the gene tagging tutorial I launced a notebook in anaconda navigator, home, launch jupyter, new, notebook python [snorkel]

I then follow the code ln[1] and ln[2] and get the error above for ln[2]

**Comment by ajratner** [comment] 2016-08-24 15:58
I don't have any experience with anaconda Navigator unfortunately, but you just need to make sure that the snorkel home directory, and that of required submodules (right now, treedlib) are on your `PATH` and `PYTHONPATH`; try just running `set_env.sh` before you start (which is called in `run.sh`)?

**Comment by Geldren1** [comment] 2016-08-25 10:33
Thank you Alex, 
I think you are on to something. But where are you inputting the command set_env.sh?
I have tried (after changing directory) in terminal, IPython and Python but none work.
I see the instructions also say to ./run.sh but I cant get this to run in terminal, IPython etc.

**Comment by ajratner** [comment] 2016-08-25 17:06
what OS are you using?

**Comment by Geldren1** [comment] 2016-08-25 23:06
Windows. Although I can run it in Linux if you recommend?

**Comment by ajratner** [comment] 2016-08-26 01:17
I would give Linux a try if you can!

**Comment by Geldren1** [comment] 2016-08-31 14:24
Hello Alex,
I have done as you suggested and I have found a new point to get stuck!
I am running in a virtualenv (called .virtualenv in accordance with the instructions) and I am using pip to install via the python-package-requirement.txt file. “pipinstall –requirement Documents/snorkel-master/python-package-requirement.txt"
I get a long list of exceptions: 
file "/home/helen/.virtualenv/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main    status self.run(options, args) 
and so on for several files and then
IOError [Errno 2] No usuable temporary directory found in ['/tmp', '/var/tmp', '/user/tmp', '/home/helen']
I have looked at the issues log in GitHub/snorkel and various searches online. The only solution I can find is not to use spaces in the path which I don't. 
Any ideas?

**Comment by ajratner** [comment] 2016-08-31 17:16
Hi @Geldren1,

I don't believe this is a Snorkel-specific issue and unfortunately I'm not quite sure how to help; have you tried installing without virtualenv?  We'll have a new release out next week as well so perhaps something will work better with the install then too!

-Alex

**Comment by Geldren1** [comment] 2016-09-01 14:12
Thank you Alex. 
I just tried installing outside of virtualenv but got the same exceptions/errors. Many thanks for your tips. I will wait until next week and have another go with the new release. Helen

**Comment by ajratner** [comment] 2016-09-07 08:40
Hi @Geldren1 I'm going to close this for now, but feel free to reopen!

**Closed by ajratner** 2016-09-07 08:40 UTC

**Comment by furmanv** [comment] 2017-05-04 12:01
Hi folks ! I also faced the same problem (no module named snorkel) while trying to run the system (run,sh) using Jupyter Notebook. Indeed the snorkel folder is contained in the snorkel-master folder, including the _init_.py file which means that snorkel can be accessed as a python package (even if _init_.py is an empty file). Thus, it seemed to me that my system path somehow ignored the snorkel folder and didn't check the files that it contained. To check this I tried:

print os.getcwd()

which returned me "...\snorkel-master\tutorials\intro" and that's what this all was about for me. The problem was that the current path was not the snorkel-master folder, but the "snorkel-master\tutorials\intro" instead. That makes sense, and in order to add the snorkel-master folder to the system path I just added: 

import sys 
sys.path.append(os.path.abspath("../.."))

which tells the system path to include also the first and the second layers of previous folders beginning from the current path. This solved the problem for me. At least no "no module named snorkel" errors appear. 

I will be very glad to see any better/clearer solution to the upper-mentioned problem. 

Kind Regards
Tigran

**Comment by ajratner** [comment] 2017-05-05 06:26
Hi @furmanv ,

Thanks for the helpful comment!

You should also be able to run `source set_env.sh` (in the snorkel root directory) to set up your paths!

**Comment by furmanv** [comment] 2017-05-05 08:03
Hi @ajratner, thanks for the fast response. 
As far as I can understand, the "set_env.sh" is already triggered when we run " ./run.sh", right? 
However, I tried running "set_env.sh" also before " ./run.sh", but got the same results, namely "ImportError: No module named snorkel".
Could be the problem is in my environment (Windows), as I work only in Windows command line and Cygwin (which is the Linux Shell for WIndows). Both returned same results. 
As stated above, the problem is solved at least for me, although it is a bit unintuitive that the system path is not being set for the intro tutorials for machines running on Windows. 

Kind Regards
Tigran

**Comment by ajratner** [comment] 2017-05-05 08:12
Hi @furmanv,

It might indeed be a Windows issue; we're unfortunately a bit behind on testing on Windows environments (and don't "officially" support Windows at the moment).

However, fglad you have a workaround, and we'll try to get to this at some point!

-Alex

**Comment by abedkhooli** [comment] 2018-01-19 17:14
This is mainly due to bash script outputting Unix path format (in set_env.sh). Windows needs semicolons to separate paths (instead of :) and "/DriveName/" is not understood. I don't know how to fix the bash shell to check for OS and write the correct path format, so I just add the two paths to my notebook for now:
sys.path.append('Drive:\\folder1\\...\\snorkel-master\\treedlib')
sys.path.append('Drive:\\folder1\\...\\snorkel-master')

**Comment by judithyueli** [comment] 2018-09-11 18:27
I have trouble locating the`set_env.sh` file? I have encountered the importing snorkel errors and thought this might be a good solution. I've tried @furmanv solution and it worked for me. 

> Hi @furmanv ,
> 
> Thanks for the helpful comment!
> 
> You should also be able to run `source set_env.sh` (in the snorkel root directory) to set up your paths!

**Comment by rjurney** [comment] 2019-06-22 02:54
I'm trying to run the unit tests on late model Ubuntu and I'm confused as to how the module treedlib is not found when it has been installed by pip?

**Comment by bhancock8** [comment] 2019-07-02 07:19
@rjurney that's a good question. When you're in the environment created by the `environment.yaml` file, what's the output you get when you type `conda list`?
