### ISSUE TITLE
KeyError: 'SNORKELHOME'

### ISSUE THREAD

**Issue by Tsmith5151** [HazyResearch/snorkel#544] opened 2017-01-22 21:42 UTC
The following error occurs when vectorizing the .tsv data file (i.e. `corpus_parser.apply(doc_preprocessor)`).

```
/Users/snorkel/snorkel/parser.pyc in __init__(self, tok_whitespace, split_newline, parse_tree)
    196         self.split_newline = split_newline
    197         self.parse_tree = parse_tree
--> 198         loc = os.path.join(os.environ['SNORKELHOME'], 'parser')
    199         cmd = ['java -Xmx4g -cp "%s/*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer --port %d --timeout %d > /dev/null'
    200                % (loc, self.port, 600000)]

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.pyc in __getitem__(self, key)
     38         if hasattr(self.__class__, "__missing__"):
     39             return self.__class__.__missing__(self, key)
---> 40         raise KeyError(key)
     41     def __setitem__(self, key, item): self.data[key] = item
     42     def __delitem__(self, key): del self.data[key]

KeyError: 'SNORKELHOME'
```

**Comment by henryre** [comment] 2017-01-22 22:08
Hey @Tsmith5151, looks like your `SNORKELHOME` environment variable isn't set. Running either the `run.sh` script or `source set_env.sh` in the top-level `snorkel` directory should set it for you.

**Comment by Tsmith5151** [comment] 2017-01-22 23:26
Hi @henryre thanks for pointing this out. On another note, when loading in the labels from `gold_labels.tsv` for the testing set in the intro tutorial, the number of "AnnotatorLabels" created is 0. Looks like it should be 220/223 and 273/279 labels loaded?

```
from load_external_annotations import load_external_labels
load_external_labels(session, Spouse, annotator_name='gold')
```

**Comment by henryre** [comment] 2017-01-23 00:14
Hi @Tsmith5151, if you run `load_external_labels(session, Spouse, annotator_name='gold')` and then rerun it a second time, the labels will not reload into the database (which is a good thing!), so that's the expected behavior. You can verify that there are 220 labels in the dev set by running

```
from snorkel.annotations import load_gold_labels
L_gold_dev = load_gold_labels(session, annotator_name='gold', split=1)
print "The dev set has {0} labels".format(np.sum(L_gold_dev.todense() != 0))
```

This is a good point to clarify though, so thanks for pointing it out. Closing this issue for now. If you run into any other issues, feel free to post a new issue.

**Closed by henryre** 2017-01-23 00:14 UTC

**Comment by Tsmith5151** [comment] 2017-01-24 18:12
Hi @henryre, is snorkel currently compatible to process searchable PDF documents?
