### ISSUE TITLE
Tutorials 2 - Error Analysis Import Error

### ISSUE THREAD

**Issue by camilix** [HazyResearch/snorkel#842] opened 2017-11-30 15:37 UTC
```
bool(sv)
Out[61]:
True

We can save the best model from the hyperparameter search with a custom name so that we can reload it later.
In [71]:

c = sv.get_selected() if sv else list(fp.union(fn))[0]
c
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-71-e46c48090d6b> in <module>()
----> 1 c = sv.get_selected() if sv else list(fp.union(fn))[0]
      2 c

/Users/Mac/Desktop/snorkel/snorkel/viewer.py in get_selected(self)
    239 
    240     def get_selected(self):
--> 241         return self.candidates[self._selected_cid]
    242 
    243 

IndexError: list index out of range
```

This was from the part -Doing Some Error Analysis

> At this point, we might want to look at some examples in one of the error buckets. For example, one of the false negatives that we did not correctly label as true mentions. To do this, we can again just use the Viewer.

Please help with this issue. Thanks!

**Comment by ajratner** [comment] 2017-12-14 05:06
Hi @camilix,

Unfortunately I'm not able to reproduce your issue. Are you able to see the `Viewer` (`sv`)? Do you have any `Candidates` selected in the viewer? Are there any other significant deviations in numbers / performance prior to this point in the tutorial, as compared to the version online?

Thanks!
Alex

**Comment by ajratner** [comment] 2019-02-19 04:42
Closing but feel free to re-open

**Closed by ajratner** 2019-02-19 04:42 UTC
Labels: bug
