### ISSUE TITLE
Use existing end extraction model on new dataset?

### ISSUE THREAD

**Issue by gabcbrown** [HazyResearch/snorkel#680] opened 2017-06-22 17:47 UTC
I've worked through the intro tutorials and produced an end extraction model that I like. Is there a way to run another dataset through this model? (Ideally, in a separate notebook). Or would it make more sense to train another model on the other dataset using the same candidate extractors and labeling functions as the first one?

**Comment by ajratner** [comment] 2017-06-23 17:20
Hi @gabcbrown,

If you want to reuse a model, `disc_model`, for predictions, you can use the [`disc_model.save`](https://github.com/HazyResearch/snorkel/blob/master/snorkel/learning/disc_learning.py#L95) method to save to disk.  Then, reconstruct the model in the new notebook and call `disc_model.load`!

However: though this works for logistic regression, there are potentially some issues with other models like the LSTM in contrib / the CDR tutorial.  We're about to pull in a big refactor ( #681 ) that will fix this though, so stay tuned there!

As for whether you should retrain the model on the new dataset- this really depends on the similarity of the new dataset with the one you used for training your model.  There's a rich literature about all this sort of "transfer learning" stuff, but I would start by trying out the above--just using your already trained model to make predictions--and then if performance on the new set if much lower than on the original dataset, I'd try retraining on the new dataset instead

**Comment by sangha123** [comment] 2017-06-23 18:39
Let us say I have a model trained on historical data and I am satisfied with its performance. As a next step we want to aggregate one day's worth of text data and pass it through snorkel (parsing, candiate extraction, etc) and use the saved model to predict on the candidates extracted. Is it possible to this, or do we have to load all the data at one go before we start the training process?

**Comment by ajratner** [comment] 2017-06-26 00:15
See the answer above: you can reload the model using the `load` function!

**Comment by JoMynta** [comment] 2017-06-27 16:00
When I tried saving and loading the model from the intro tutorial I got an error:
AttributeError: 'SparseLogisticRegression' object has no attribute 'k'
Do you know what went wrong there?

**Comment by ajratner** [comment] 2017-06-28 02:58
Sorry the saving / loading functionalities will be upgraded / fixed with
the v0.6 release due out end of this week! This particular change is
actually already fixed but just not yet merged to master, sorry for the
delay!

**Comment by ajratner** [comment] 2017-07-10 05:44
Should be fixed with v0.6; also in the intro tutorial now!

**Closed by ajratner** 2017-07-10 05:44 UTC

**Comment by pidugusundeep** [comment] 2018-05-22 13:35
1. Can we use the existing model and load the model with .load() and train with a new train data set?
2. Can we directly use the model to give it a dump of documents to figure out the candidates or do we need to declare the candidate class and extract the possible candidates and then pass it that data to the model ?
3. Can we combine multiple models and generate a single model for all the candidate extraction from a set of documents text ? ( if every model should have the particular candidate class data passed as a paramater then this is not valid)

**Comment by alexandrateste** [comment] 2019-09-09 17:01
Re-opening this issue.
I am using Snorkel version 0.9.1 on a macbook pro version 10.14.6.

I created a LabelModel object and saved it:
```
label_model = LabelModel(cardinality=2, verbose=True)
label_model.fit(L_train=L_train, n_epochs=1000, lr=0.001, log_freq=100, seed=123)
label_model.save('./saved_label_model')
```

I then tried to load and use it on my test data:
```
testlm = LabelModel(verbose=False)
testlm.load('./saved_label_model')
testlm.score(L=L_test, Y=y_test)["accuracy"]
```
but got an AttributeError:
```
AttributeError: 'LabelModel' object has no attribute 'c_tree'
```

I also tried extracting the weights
```
testlm.get_weights()
```
but got another error
```AttributeError: 'LabelModel' object has no attribute 'm'```


Running `.fit()` on `testlm`, with the original data seemed to fix the problem:
```testlm.fit(L_train=L_train, n_epochs=1000, lr=0.001, log_freq=100, seed=123)```

However, this required having access to the original data. This is problematic if I want to reuse my model where I don't have access to those original data.

Since the [code](https://github.com/snorkel-team/snorkel/blob/master/snorkel/labeling/model/label_model.py#L945) seems to be based on Pytorch, I also tried saving the state dictionary ```label_model.save('./saved_label_model_state_dict', label_model.state_dict())```, but got another error ```TypeError: save() takes 2 positional arguments but 3 were given```.

Could you then please tell me what to do after
```
testlm = LabelModel(verbose=False)
testlm.load('./saved_label_model')
```
so I can run `testlm` on my test data?

Thank you for your help.
