### ISSUE TITLE
Character-level parsing?

### ISSUE THREAD

**Issue by jbkoh** [HazyResearch/snorkel#1008] opened 2018-08-14 20:34 UTC
Hi,

I am trying to use Snorkel for my problem settting where I need character-level mappings. What I want is every character being a candidate while keeping Ngrams for its context. For example,
If we are given, "AB CD",
I would like to be candidate-context pairs with bigram something like
- Candidate “A” with context [“A”]
- Candidate “B” with context [“A”, “B”]
- Candidate “ “ with context [“B”, “ “]
- Candidate “C” with context [“ ”, “C”]
- Candidate “D” with context [“C”, “D”]
, assuming individual character has some meaning. (in many cases the characters are not separated out by either spaces or special characters.)

I am trying to figure out how to do this in Snorkel. Below is my attempt, but it seems incorrect based on the result. I'd appreciate if I can get any hint here.

The default parsers seem not supporting the character level parsing, so I ended up writing my ``fn`` to parse the sentences like 
```python
def parser(sentence):
    sentence['words'] = [c for c in ''.join(sentence['words'])]
    return sentence
doc_preprocessor = TSVDocPreprocessor('some_data.tsv') 
corpus_parser = CorpusParser(fn=parser)
corpus_parser.apply(doc_preprocessor)
```
This will delimite sentences into characters. 

Then, I want to have each character as a candidate, so I wrote a naive regex matcher like
```python
simple_matcher = RegexMatchEach(attrib='words', rgx='.')
cand_extractor = CandidateExtractor(some_cand,
                                    Ngrams(n_max=2),
                                    simple_matcher,
                                    symmetric_relations=False)
```

Here I assumed that the ``simple_matcher`` is applied to every item in “words”, which is supposed to be individual characters. However, it looks like is not working. In SentenceNgramView, it still shows the candidates at the "word" level not "character" level. More precisely, It selects the current character and previous word as a candidate like this
- “AB”
- “AB C”

as candidates from the above code and the sentence.

I feel at this moment that I may not understand the role of each function. I'd appreciate if I can get any help.

Thanks a lot!

**Comment by ajratner** [comment] 2019-02-19 05:21
Hi @jbkoh thanks for the well-documented issue!

At a high level, to start, there are three parts:
1. Preprocess the input data into a set of `Context` objects
2. Define a `CandidateSpace`, i.e. a set of possible `Candidate` objects (objects to train the end model to classify) in each `Context`
3. Define a `Matcher` to select a subset (i.e. filter down) this candidate space.

So it sounds like what you want to do is define each word as the context in (1), define each individual character as a potential candidate in (2), and then have a trivial identity filter in (3)?

In the particular way that you're going about it above, I believe the issue is that the methods use other attributes of the sentence object (in particular the character offsets), however you're only rewriting the `words` attribute.

However, overall: without more knowledge of your application, don't know whether this is a good fit for the particular data model being used in Snorkel.  Either way hope this helps!  Closing for now, but happy to re-open

**Closed by ajratner** 2019-02-19 05:21 UTC
