### ISSUE TITLE
document text as a candidate

### ISSUE THREAD

**Issue by yayitswei** [HazyResearch/snorkel#755] opened 2017-08-03 08:20 UTC
Hi, is there a simple way to use the entire document text as a candidate, even if it spans multiple sentences? Couldn't figure out a good way to do that after going through the tutorials.

I have the following code:

```
from snorkel.models import candidate_subclass
Question = candidate_subclass('Question', ['question'])

from snorkel.models import Context, Candidate
from snorkel.contrib.models.text import RawText
from snorkel.models import Document

for doc in session.query(Document).order_by(Document.name).all():
    q = Question(question=doc)
    session.add(q)

session.commit()

from snorkel.viewer import Viewer
candidates = session.query(Question).all()
v = Viewer(candidates, session)
v
```
And I'm getting this error: `AttributeError: 'Document' object has no attribute 'char_start'
`, can you tell me what I'm missing?

Thanks!

**Comment by ajratner** [comment] 2017-08-03 16:44
Hi @yayitswei ,

Check out the crowdsourcing tutorial for one example!

**Comment by maryamre** [comment] 2017-12-11 17:04
Hi @ajratner, 
I am also looking for a simple way to use the entire document text as a candidate, I did look at crowdsourcing tutorial and tried to implement that example but it did not work since it is working on spark. I created a custom Candidate sub-class and wanted to extract all the text without any filter/ Matcher. Just wondering if there is an easy way to use CandidateExtractor and extract all the text?
Thanks!

**Comment by ajratner** [comment] 2017-12-13 08:07
Hi @yayitswei @maryamre 

Sorry for the delayed response!  First of all, to be more specific than my original quick response, here's the class I was thinking of: https://github.com/HazyResearch/snorkel/blob/master/snorkel/contrib/models/text.py

@yayitswei I believe the issue is that the `Viewer` does not yet work with full-doc objects. In case of interest:
- The `Viewer` class only has one dependency on `char_start` (here: https://github.com/HazyResearch/snorkel/blob/master/snorkel/viewer.py#L74), and just used for sorting candidates- this could easily be circumvented
- Then, you would just need to make a custom sub-class of `Viewer` just like `SentenceNgramViewer`

**Comment by jmugan** [comment] 2018-02-19 17:40
I'm having the same problem. I'm building off the crowdsourcing tutorial to classify Tweets and I'm getting the error `AttributeError: 'RawText' object has no attribute 'char_start'`

The error comes from the last line of this code 
```
from snorkel.annotations import LabelAnnotator
labeler = LabelAnnotator(lfs=[LF_rule])
L_train = labeler.apply(split=0, lfs=[LF_rule], parallelism=1)
```

**Comment by ajratner** [comment] 2019-02-19 02:50
Closing this for now (think it is fixed)- happy to re-open if not!

**Closed by ajratner** 2019-02-19 02:50 UTC
Labels: Q&A

**Comment by mlamee** [comment] 2019-05-02 18:04
Hi, I'm having the same issue. I am trying to classify sentences. I followed the crowd sourcing tutorial and have produced some labeling functions, trained the model, etc. Everything seems to be working except the viewer! I want to use the viewer to manually correct some of my labels but I'm getting the error that `AttributeError: 'RawText' object has no attribute 'char_start'`. Is there any solution to this problem? I need to see examples to understand. Thanks

`text=pd.read_csv('/PATH_TO_CSV', delimiter='|')`
text is a data frame that contains sentences
`condlist=['when','if','only','reimburse','bill','reimbursable','pay','payable']
def findcond(x, condlist):
    x=x.strip()
    if x[-1]=='.':
        x=x[0:-1]
    return any([w in x.split() for w in condlist])`

`from snorkel.models import candidate_subclass`
Two possible classes
Creating Snorkel candidate object for sentenses.
`Sent = candidate_subclass('Sent', ['sent'])`

`from snorkel.models import Context, Candidate
from snorkel.contrib.models.text import RawText`

 Make sure DB is cleared
`session.query(Context).delete()
session.query(Candidate).delete()`

Generate and store the sentence candidates to be classified
`total_sent = text.shape[0]
sent_list = []
test_split = total_sent*0.1
for i, t in text.iterrows():
    print(t.sentence)
    split = 1 if i <= test_split else 0
    raw_text = RawText(stable_id=t.ID, name=t.ID, text=t.sentence)
    sent = Sent(sent=raw_text, split=split)
    sent_list.append(sent)
    session.add(sent)
session.commit()`

labeling functions
`def if_lf(t): 
        return 1 if findcond(t.sent.text,['if']) else 0
def only_lf(t): 
        return 1 if findcond(t.sent.text,['only']) else 0
def when_lf(t): 
        return 1 if findcond(t.sent.text,['when']) else 0
def reimburse_lf(t): 
        return 1 if findcond(t.sent.text,['reimburse']) else 0
def bill_lf(t): 
        return 1 if findcond(t.sent.text,['bill']) else 0
def reimbursable_lf(t): 
        return 1 if findcond(t.sent.text,['reimbursable']) else 0
def pay_lf(t): 
        return 1 if findcond(t.sent.text,['pay']) else 0
def payable_lf(t): 
        return 1 if findcond(t.sent.text,['payable']) else 0

lfs=[if_lf, only_lf, when_lf, reimburse_lf, bill_lf, reimbursable_lf, pay_lf, payable_lf]
labeler = LabelAnnotator(lfs=lfs)
%time L_train = labeler.apply(split=0)
L_train`

`from snorkel.learning import GenerativeModel
gen_model = GenerativeModel()
gen_model.train(L_train, epochs=100, decay=0.95, step_size=0.1 / L_train.shape[0], reg_param=1e-6)`

Now I want to manually look at the labels I have generated
`all_sents=session.query(Sent).all()
from snorkel.viewer import Viewer
v=Viewer(set(all_sents), session)
v`

But I'm getting the error:
AttributeError                            Traceback (most recent call last)
<ipython-input-76-ff470f33f7ce> in <module>
----> 1 v=Viewer(set(all_sents), session)
      2 v

/anaconda3/envs/snorkel/lib/python3.6/site-packages/snorkel/viewer/__init__.py in __init__(self, candidates, session, gold, n_per_page, height, annotator_name)
     76         # We get the sorted candidates and all contexts required, either from unary or binary candidates
     77         self.gold       = list(gold)
---> 78         self.candidates = sorted(list(candidates), key=lambda c : c[0].char_start)
     79         self.contexts   = list(set(c[0].get_parent() for c in self.candidates + self.gold))
     80 

/anaconda3/envs/snorkel/lib/python3.6/site-packages/snorkel/viewer/__init__.py in <lambda>(c)
     76         # We get the sorted candidates and all contexts required, either from unary or binary candidates
     77         self.gold       = list(gold)
---> 78         self.candidates = sorted(list(candidates), key=lambda c : c[0].char_start)
     79         self.contexts   = list(set(c[0].get_parent() for c in self.candidates + self.gold))
     80 

AttributeError: 'RawText' object has no attribute 'char_start'

**Comment by SElghazolyMM** [comment] 2019-05-21 20:56
I am having a similar issue. In addition, 
accuracy = gen_model.score(L_train, train_cand_labels)
yields three values for accuracy, all greater than 1.
